/* EISENHORN Trainer — Übungsdaten
   L = [Name, Slug] aller Kraftübungen von eisenhorn.com/de-de/training/kraftuebungen/
   Slugs mit Präfix 2xx- sind DS-spezifische Übungen (zwei Schienen).
   DETAIL = ausformulierte Übungen. Fehlt ein Eintrag, klassifiziert die App
   Muskelgruppe und Rüstart automatisch aus dem Namen — im Detail korrigierbar. */
window.EH_DATA = {
L: [
["Schulterdrücken vor dem Kopf","schulterdruecken"],
["Latzug in den Nacken","latzug-in-den-nacken"],
["Latzug zur Brust","latzug-zur-brust"],
["Brustdrücken stehend","brustdruecken-stehend"],
["Bizepscurls stehend","bizepscurls"],
["Aufrechtes Rudern mit engem Griff","aufrechtes-rudern-mit-engem-griff"],
["Ruderzug seitlich stehend","ruderzug-seitlich-stehend"],
["Trizepsübung mit Griffstange","uebungen-fuer-den-trizeps"],
["Hängendes Beinheben","haengendes-beinheben-mit-angewinkelten-beinen"],
["Recrunch mit Griffband","recrunch-mit-griffband"],
["Trizepsübung mit Griffband kniend","011-trizepsuebung-mit-griffband-kniend"],
["Rumpfrotation","rumpfrotation"],
["Crunches","crunches"],
["Kreuzheben mit Griffstange","kreuzheben-mit-griffstange-deadlift"],
["Ausfallschritte","ausfallschritte"],
["Einbeinige Kniebeuge mit Entlastung","einbeinige-kniebeuge-mit-entlastung"],
["Einbeinige Beinpresse","einbeinige-beinpresse"],
["Einbeinige rückwärtige Beinpresse","einbeinige-rueckwaertige-beinpresse"],
["Stehendes Wadenheben","stehendes-wadenheben"],
["Beinbeuger liegend","beinbeuger-liegend"],
["Hackenschmidt Kniebeuge","hackenschmidt-kniebeuge"],
["Hängendes Beinheben mit gestreckten Beinen","haengendes-beinheben-mit-gestreckten-beinen"],
["Hüftheben seitlich","hueftheben-seitlich"],
["Progressives Kreuzheben mit Griffband","progressives-kreuzheben-mit-griffband"],
["Bankdrücken (Brustdrücken)","bankdruecken-brustdruecken"],
["Beinpresse","beinpresse"],
["Frontkniebeugen","kniebeugen"],
["Adduktion mit Griffband","adduktion-mit-griffband"],
["Rudern vorgebeugt mit Untergriff","rudern-vorgebeugt-mit-untergriff"],
["Klimmzug auf die Brust","klimmzug-auf-die-brust"],
["Einbeinige Kniebeuge am Horn","031-einbeinige-kniebeuge-am-horn"],
["Rudern seitlich einarmig","rudern-seitlich-einarmig"],
["Brustdrücken seitlich","brustdruecken-seitlich"],
["Innenrotation mit Seilzug","innenrotation-mit-seilzug"],
["Hüftheben","hueftheben"],
["Aussenrotation mit Seilzug","aussenrotation-mit-seilzug"],
["Rudern vorgebeugt mit Obergriff","rudern-vorgebeugt-mit-obergriff"],
["Innenrotation seitlich mit Griffband","innenrotation-seitlich-mit-griffband"],
["Aussenrotation seitlich mit Griffband","aussenrotation-seitlich-mit-griffband"],
["Beckenheben liegend","beckenheben-liegend"],
["Aufrechtes Rudern mit breitem Griff","aufrechtes-rudern-mit-breitem-griff"],
["Trizepsübung mit Griffband","trizepsuebung-mit-griffband"],
["Schulterdrücken hinter dem Kopf","schulterdruecken-hinter-dem-kopf"],
["Liegestütze mit einem Bein im Griffband","liegestuetze-mit-einem-bein-im-griffband"],
["Einbeiniges Kreuzheben einarmig","einbeiniges-kreuzheben-einarmig"],
["Sumo-Kreuzheben mit Griffstange","sumo-kreuzheben-deadlifts-mit-griffstange"],
["Rumänisches Kreuzheben","kreuzheben-deadlifts-mit-gestreckten-beinen"],
["Plank to pike","plank-to-pike"],
["Ausfallschritte mit Griffband","ausfallschritte-mit-griffband"],
["Wadenheben sitzend","wadenheben-sitzend"],
["Unterarm-Curls mit Obergriff","unterarm-curls-mit-obergriff"],
["Unterarm-Curls hinter dem Rücken","unterarm-curls-hinter-dem-ruecken"],
["Negativ Bankdrücken mit angehobenen Beinen","negativ-bankdruecken-mit-angehobenen-beinen"],
["Dips mit Gewicht","dips-mit-gewicht"],
["Hängendes Beinheben mit angewinkelten Beinen","055-haengendes-beinheben-mit-angewinkelten-beinen"],
["Trizepsübung mit langem Griffband","trizepsuebung-mit-langem-griffband"],
["Schienbeinheben sitzend","schienbeinheben-sitzend"],
["Einbeinige Kniebeugen seitlich","einbeinige-kniebeugen-seitlich"],
["Crunches mit Griffband","crunches-mit-griffband"],
["Butterfly","butterfly"],
["Dips mit Griffband","dips-mit-griffband"],
["Bauchcrunches seitlich","bauchcrunches-seitlich"],
["Recrunch mit Griffband (kniend)","063-recrunch-mit-griffband"],
["Trizepsübung mit Griffband II","trizepsuebung-mit-griffband-2"],
["Überkopf-Ausfallschritte","ueberkopf-ausfallschritte"],
["Trizepsübung mit Griffstange kniend","066-trizepsuebung-mit-griffstange-kniend"],
["Nackenheben hinten","nackenheben-hinten"],
["Rudern einarmig","rudern-einarmig"],
["Bizepscurls mit Körpergewicht","bizepscurls-mit-koerpergewicht"],
["Ausfallschritte nach vorne","ausfallschritte-nach-vorne"],
["Schulterheben hinten","schulterheben-hinten"],
["Schulterdrücken hinter dem Kopf sitzend","072-schulterdruecken-hinter-dem-kopf"],
["Dips mit Griffband tief","073-dips-mit-griffband-tief"],
["Hammer Curls","hammer-curls"],
["Hängender Ruderzug mit angewinkelten Beinen","haengender-ruderzug-mit-angewinkelten-beinen"],
["Schulterdrücken hinter dem Kopf mit Griffband","schulterdruecken-hinter-dem-kopf-mit-griffband"],
["Ausfallschritte mit Griffstange","ausfallschritte-mit-griffstange"],
["Liegestütze mit Griffband","liegestuetze-mit-griffband"],
["Trizepsdrücken","trizepsdruecken"],
["Mountain Climbers","mountain-climbers"],
["Schulterdrücken sitzend","schulterdruecken-sitzend"],
["Rumpfbeugen seitlich","rumpfbeugen-seitlich"],
["Einarmige Bizepscurls","einarmige-bizepscurls"],
["Rudern mit Griffband","rudern-mit-griffband"],
["Bankdrücken in Brückenstellung","bankdruecken-in-brueckenstellung"],
["Trizepsübung mit Griffband einarmig","trizepsuebung-mit-griffband-einarmig"],
["Beinbeuger mit Griffband","beinbeuger-mit-griffband"],
["Plank Jacks","plank-jacks"],
["Schulterheben vorne","schulterheben-vorne"],
["Trizepsübung mit Griffstange Untergriff","trizepsuebung-mit-griffstange-im-untergriff"],
["Trizepsübung mit Griffband einarmig II","trizepsuebung-mit-griffband-einarmig-2"],
["Wadenheben stehend exzentrisch","wadenheben-stehend-exzentrisch"],
["Unterarmstütz mit Griffband","unterarmstuetz-mit-griffband"],
["Trizepsübung mit Griffstange Untergriff kniend","094-trizepsuebung-mit-griffstange-untergriff-kniend"],
["Latzug mit Griffband","latzug-mit-griffband"],
["Einbeiniges Kreuzheben","einbeiniges-kreuzheben"],
["Bizepscurls mit Griffband","bizepscurls-mit-griffband"],
["Überkopf-Kniebeugen","ueberkopf-kniebeugen-overhead-squats"],
["Schulterdrücken sitzend mit angehobenen Füssen","schulterdruecken-sitzend-mit-angehobenen-fuessen"],
["Schulterdrücken mit engem Griff","schulterdruecken-mit-engem-griff"],
["Ausfallschritte mit Stufe","ausfallschritte-mit-stufe"],
["Laufschritt mit Griffband","laufschritt-mit-griffband"],
["Liegestütze mit Griffband und Griffstange","liegestuetze-mit-griffband-und-griffstange"],
["Bizepscurls mit Griffstange und Seilzug","bizepscurls-mit-griffstange-und-seilzug"],
["Einarmige Bizepscurls am Seilzug","einarmige-bizepscurls-am-seilzug"],
["Seitenheben am Seilzug","seitenheben-am-seilzug"],
["Flys einarmig am Seilzug","flys-einarmig-am-seilzug"],
["Einarmiges Trizepsdrücken","einarmiges-trizepsdruecken"],
["Rumpfrotation am Seilzug","rumpfrotation-am-seilzug"],
["Schulterdrücken mit engem Griff sitzend","110-schulterdruecken-mit-engem-griff-sitzend"],
["Latzug in den Nacken sitzend","111-latzug-in-den-nacken-sitzend"],
["Crossover Crunch am Seilzug","crossover-crunch-am-seilzug"],
["Russian Twist am Seilzug","russian-twist-am-seilzug"],
["Seitliche Crunches am Seilzug","seitliche-crunches-am-seilzug"],
["Latzug zur Brust sitzend","115-latzug-zur-brust-sitzend"],
["Facepulls am Seilzug","facepulls-am-seilzug"],
["Einarmiger Latzug am Seilzug","einarmiger-latzug-am-seilzug"],
["Stehendes Rudern am Seilzug","stehendes-rudern-am-seilzug"],
["Stehendes Rudern mit Untergriff am Seilzug","stehendes-rudern-mit-untergriff-am-seilzug"],
["Einarmiges Rudern mit Obergriff am Seilzug","einarmiges-rudern-mit-obergriff-am-seilzug"],
["Rudern im Ausfallschritt am Seilzug","rudern-im-ausfallschritt-am-seilzug"],
["Stehender Ruderzug mit Seilzug","stehender-ruderzug-mit-seilzug"],
["Kickbacks am Seilzug","kickbacks-am-seilzug"],
["Abduktion am Seilzug","abduktion-am-seilzug"],
["Adduktion am Seilzug","adduktion-am-seilzug"],
["Beinstrecker am Seilzug","beinstrecker-am-seilzug"],
["Trizepsdrücken am Seilzug","trizepsdruecken-am-seilzug"],
["Überkopf-Trizepsdrücken am Seilzug","ueberkopf-trizepsdruecken-am-seilzug"],
["Schulterdrücken vor dem Kopf (DS)","200-schulterdruecken-vor-dem-kopf"],
["Vorgebeugtes Rudern mit Griffstange","201-vorgebeugtes-rudern-mit-griffstange"],
["Frontkniebeugen (DS)","202-frontkniebeugen"],
["Kniebeugen (DS)","203-kniebeugen"],
["Kreuzheben (DS)","204-kreuzheben"],
["Rumänisches Kreuzheben (DS)","205-rumaenisches-kreuzheben"],
["Latzug mit Griff am Horn","206-latzug-mit-griff-am-horn"],
["Latzug alternierend mit Griff am Horn","207-latzug-alternierend-mit-griff-am-horn"],
["Latzug auf die Brust mit Griffstange","208-latzug-auf-die-brust-mit-griffstange"],
["Brustdrücken stehend mit Griffstange","209-brustdruecken-stehend-mit-griffstange"],
["Schulterdrücken am Horn alternierend","210-schulterdruecken-am-horn-alternierend"],
["Rudern vorgebeugt mit Griff am Horn","211-rudern-vorgebeugt-mit-griff-am-horn"],
["Vorgebeugtes Rudern am Horn alternierend","212-vorgebeugtes-rudern-mit-griff-am-horn-alternierend"],
["Explosives Brustdrücken am Horn alternierend","213-explosives-brustdruecken-am-horn-alternierend"],
["Dips (DS)","214-dips"],
["Kreuzheben mit Griff am Horn","215-kreuzheben-mit-griff-am-horn"],
["Rumänisches Kreuzheben mit Griff am Horn","216-rumaenisches-kreuzheben-mit-griff-am-horn"],
["Alternierende Dips stehend","217-alternierende-dips-stehend"],
["Farmer's walk","218-farmers-walk"],
["Wadenheben mit Griff am Horn","219-wadenheben-mit-griff-am-horn"],
["Shrugs alternierend mit Griff am Horn","220-shrugs-alternierend-mit-griff-am-horn"],
["Shrugs mit Griff am Horn","221-shrugs-mit-griff-am-horn"],
["Fliegende mit Seilzug von unten","222-fliegende-mit-seilzug-von-unten"],
["Überkopf-Trizeps-Extensions mit Seilzug","223-ueberkopf-trizeps-extensions-mit-seilzug"],
["Reverse Flys vorgebeugt mit Seilzug","224-reverse-flys-vorgebeugt-mit-seilzug"],
["Alternierendes Rudern vorgebeugt mit Seilzug","225-alterniederendes-rudern-vorgebeugt-mit-seilzug"],
["Schulterrotatoren alternierend am Seilzug","226-schulterrotatoren-alternierend-am-seilzug"],
["Reverse Flys asymmetrisch am Seilzug","227-reverse-flys-asymmetrisch-am-seilzug"],
["Klimmzug mit Griffstange","228-klimmzug-mit-griffstange"],
["Bankdrücken mit Griffstange","229-bankdruecken-mit-griffstange"],
["Bankdrücken mit Griff am Horn","230-bankdruecken-mit-griff-am-horn"],
["Alternierendes Bankdrücken mit Griff am Horn","231-alternierendes-bankdruecken-mit-griff-am-horn"],
["Schulterrotatoren parallel am Seilzug","232-schulterrotatoren-parallel-am-seilzug"]
],

DETAIL: {
"schulterdruecken":{m:"Schultern",r:"Stange",mu:[["Primär","Schultern"],["Sekundär","Trizeps"]],s:[
 ["Vorbereitung","Schlitten so einstellen, dass die Griffstange auf Höhe deiner Oberbrust liegt."],
 ["Ausgangsposition","Stabiler Stand, Rücken gerade, Hände weit aussen an der Griffstange."],
 ["Ausführung","Gleichmässig nach oben drücken bis die Arme gestreckt sind. Langsam zurückführen — kurz vor dem unteren Punkt wieder drücken."]],
 t:"Kein Hohlkreuz, Rumpfspannung halten, Schultern unten lassen."},
"kreuzheben-mit-griffstange-deadlift":{m:"Rücken",r:"Stange",mu:[["Primär","Rücken"],["Sekundär","Beine"]],s:[
 ["Vorbereitung","Schlitten ganz unten, Griffstange auf Schienbeinhöhe."],
 ["Ausgangsposition","Hüftbreiter Stand, Brust raus, Rücken neutral."],
 ["Ausführung","Über Hüfte und Knie strecken, Stange körpernah führen, kontrolliert ablassen."]],
 t:"Die Bewegung startet aus den Beinen, nicht aus dem Rücken."},
"hackenschmidt-kniebeuge":{m:"Beine",r:"Ohne",mu:[["Primär","Quadrizeps"],["Sekundär","Gesäss"]],s:[
 ["Vorbereitung","Schulterpolster einsetzen, Füsse leicht vorgesetzt."],
 ["Ausgangsposition","Rücken flach am Schlitten, Rumpf fest."],
 ["Ausführung","Kontrolliert bis mindestens 90° absenken, kraftvoll strecken ohne durchzudrücken."]],
 t:"Knie folgen der Fussspitze."},
"latzug-zur-brust":{m:"Rücken",r:"Stange",mu:[["Primär","Latissimus"],["Sekundär","Bizeps"]],s:[
 ["Vorbereitung","Seilzug oben einhängen, Griffstange weit fassen."],
 ["Ausgangsposition","Sitzend, Oberkörper leicht zurück."],
 ["Ausführung","Stange zur Oberbrust ziehen, Schulterblätter zusammen, langsam zurück."]],
 t:"Nicht mit Schwung arbeiten."},
"bankdruecken-brustdruecken":{m:"Brust",r:"Stange",mu:[["Primär","Brust"],["Sekundär","Trizeps"]],s:[
 ["Vorbereitung","Bank mittig unter der Griffstange positionieren."],
 ["Ausgangsposition","Schulterblätter zusammen, Füsse fest am Boden."],
 ["Ausführung","Stange zur Brust senken, gleichmässig nach oben drücken."]],
 t:"Ellenbogen nicht komplett ausflaren."},
"bizepscurls":{m:"Arme",r:"Stange",mu:[["Primär","Bizeps"],["Sekundär","Unterarm"]],s:[
 ["Vorbereitung","Griffstange unten am Schlitten, Untergriff."],
 ["Ausgangsposition","Aufrechter Stand, Ellenbogen am Körper."],
 ["Ausführung","Nur den Unterarm beugen, oben kurz halten, langsam ablassen."]],
 t:"Der Oberkörper bleibt ruhig."},
"trizepsdruecken-am-seilzug":{m:"Arme",r:"Seilzug",mu:[["Primär","Trizeps"],["Sekundär","Schulter"]],s:[
 ["Vorbereitung","Seilzug hoch einhängen."],
 ["Ausgangsposition","Leicht vorgebeugt, Ellenbogen fixiert."],
 ["Ausführung","Unterarme nach unten strecken, kontrolliert zurück."]],
 t:"Die Ellenbogen wandern nicht nach vorne."},
"beinpresse":{m:"Beine",r:"Ohne",mu:[["Primär","Beine"],["Sekundär","Gesäss"]],s:[
 ["Vorbereitung","Rückenlage auf der Bank, Füsse auf der Plattform."],
 ["Ausgangsposition","Knie ca. 90°, unterer Rücken aufliegend."],
 ["Ausführung","Kraftvoll strecken ohne die Knie zu blockieren, langsam beugen."]],
 t:"Die Fersen bleiben auf der Platte."},
"klimmzug-auf-die-brust":{m:"Rücken",r:"Ohne",mu:[["Primär","Latissimus"],["Sekundär","Bizeps"]],s:[
 ["Vorbereitung","Griffband als Entlastung einhängen."],
 ["Ausgangsposition","Weiter Obergriff, Schultern aktiv."],
 ["Ausführung","Brust zur Stange ziehen, kontrolliert ablassen."]],
 t:"Entlastungsstufe reduzieren statt Wiederholungen abbrechen."},
"222-fliegende-mit-seilzug-von-unten":{m:"Brust",r:"Seilzug",mu:[["Primär","Brust"],["Sekundär","Schulter"]],s:[
 ["Vorbereitung","Beide Seilzüge unten einhängen."],
 ["Ausgangsposition","Schrittstellung, Arme leicht gebeugt."],
 ["Ausführung","Arme in weitem Bogen nach oben zusammenführen."]],
 t:"Bogen führen, nicht drücken."},
"crunches":{m:"Bauch",r:"Ohne",mu:[["Primär","Bauch"],["Sekundär","Hüftbeuger"]],s:[
 ["Vorbereitung","Griffband oben einhängen, kniend davor."],
 ["Ausgangsposition","Hände am Band neben dem Kopf."],
 ["Ausführung","Oberkörper einrollen, kurz halten, kontrolliert zurück."]],
 t:"Bewegung aus dem Bauch, nicht aus den Armen."},
"stehendes-wadenheben":{m:"Beine",r:"Ohne",mu:[["Primär","Waden"],["Sekundär","—"]],s:[
 ["Vorbereitung","Schulterpolster einsetzen, Fussballen auf der Kante."],
 ["Ausgangsposition","Beine gestreckt, Rumpf fest."],
 ["Ausführung","Fersen maximal heben, oben halten, tief ablassen."]],
 t:"Voller Bewegungsumfang zählt mehr als Last."},
"218-farmers-walk":{m:"Ganzkörper",r:"Ohne",mu:[["Primär","Griff / Rumpf"],["Sekundär","Trapez"]],s:[
 ["Vorbereitung","Griffe am Horn einhängen."],
 ["Ausgangsposition","Aufrecht, Schultern zurück."],
 ["Ausführung","Spannung halten und gehen, Rumpf durchgehend fest."]],
 t:"Lieber Zeit unter Spannung als maximale Last."},
"rumpfrotation-am-seilzug":{m:"Bauch",r:"Seilzug",mu:[["Primär","Schräge Bauchmuskeln"],["Sekundär","Rumpf"]],s:[
 ["Vorbereitung","Seilzug auf Brusthöhe."],
 ["Ausgangsposition","Seitlich zum Gerät, Arme gestreckt."],
 ["Ausführung","Aus dem Rumpf rotieren, die Hüfte bleibt weitgehend stabil."]],
 t:"Langsam zurückführen."},
"facepulls-am-seilzug":{m:"Schultern",r:"Seilzug",mu:[["Primär","Hintere Schulter"],["Sekundär","Oberer Rücken"]],s:[
 ["Vorbereitung","Seilzug auf Kopfhöhe."],
 ["Ausgangsposition","Leichte Schrittstellung, Arme gestreckt."],
 ["Ausführung","Zum Gesicht ziehen, Ellenbogen hoch, Schulterblätter zusammen."]],
 t:"Die beste Gegenübung zu allem Drücken."},
"201-vorgebeugtes-rudern-mit-griffstange":{m:"Rücken",r:"Stange",mu:[["Primär","Oberer Rücken"],["Sekundär","Bizeps"]],s:[
 ["Vorbereitung","Griffstange unten am Schlitten."],
 ["Ausgangsposition","Hüfte gebeugt, Rücken neutral."],
 ["Ausführung","Stange zum Bauch ziehen, Schulterblätter zusammen, kontrolliert ablassen."]],
 t:"Oberkörperwinkel konstant halten."}
}
};

/* Ergänzende Inhalte je Übung.
   sk = Beanspruchte Muskulatur als Skala [Name, Anteil 0–100]
   b  = "Bitte beachten"
   dt = "Übung im Detail"
   v  = "Weitere Varianten" (Slugs aus L)
   p  = Bewegungsmuster fürs Schema: druck|zug|beuge|hebe|curl|rudern|rotation|rumpf */
window.EH_DATA.EXTRA = {
"schulterdruecken":{p:"druck",sk:[["Schultern",100],["Trizeps",65],["Rumpf",40]],
 b:"Nicht bei akuten Schulterbeschwerden. Die Stange vor dem Kopf führen, nicht in den Nacken, wenn die Schultermobilität begrenzt ist.",
 dt:"Die Overhead Press ist eine der fünf Grundübungen. Über den Kopf drücken aktiviert vordere und seitliche Deltamuskeln intensiv, der Trizeps unterstützt, und der Rumpf hält den Oberkörper aufrecht — dadurch verbessert die Übung nebenbei die Haltung.",
 v:["schulterdruecken-hinter-dem-kopf","schulterdruecken-sitzend","schulterdruecken-mit-engem-griff","210-schulterdruecken-am-horn-alternierend"]},
"kreuzheben-mit-griffstange-deadlift":{p:"hebe",sk:[["Rücken",100],["Beine",85],["Gesäss",70],["Griff",45]],
 b:"Rücken nie runden. Im Zweifel eine Stufe zurück und die Technik sauber halten.",
 dt:"Kreuzheben ist die Ganzkörperübung schlechthin: hintere Kette, Rumpf und Griffkraft in einer Bewegung. Ab Stufe 8 arbeitet die ansteigende Kraftkurve genau dort, wo du am stärksten bist — im oberen Bewegungsdrittel.",
 v:["sumo-kreuzheben-deadlifts-mit-griffstange","kreuzheben-deadlifts-mit-gestreckten-beinen","einbeiniges-kreuzheben","215-kreuzheben-mit-griff-am-horn"]},
"hackenschmidt-kniebeuge":{p:"beuge",sk:[["Quadrizeps",100],["Gesäss",70],["Waden",35]],
 b:"Knie nicht nach innen fallen lassen. Tiefe nur so weit, wie der untere Rücken flach bleibt.",
 dt:"Durch die geführte Bewegung am Schlitten liegt der Fokus stärker auf dem Quadrizeps als bei der freien Kniebeuge, während der Rücken entlastet bleibt.",
 v:["203-kniebeugen","202-frontkniebeugen","einbeinige-kniebeuge-mit-entlastung","ueberkopf-kniebeugen-overhead-squats"]},
"latzug-zur-brust":{p:"zug",sk:[["Latissimus",100],["Bizeps",60],["Oberer Rücken",55]],
 b:"Nicht in den Nacken ziehen, wenn die Schulter empfindlich ist.",
 dt:"Der Latzug baut die Breite des Rückens auf und ist die zugängliche Alternative zum Klimmzug, weil die Last frei wählbar ist.",
 v:["latzug-in-den-nacken","115-latzug-zur-brust-sitzend","latzug-mit-griffband","einarmiger-latzug-am-seilzug"]},
"bankdruecken-brustdruecken":{p:"druck",sk:[["Brust",100],["Trizeps",65],["Schultern",50]],
 b:"Schulterblätter fixiert halten, die Stange nicht auf der Brust abfedern.",
 dt:"Die klassische Druckübung für den Oberkörper. Am Schlitten läuft die Bewegung geführt, dadurch bleibt sie auch ohne Trainingspartner sicher.",
 v:["negativ-bankdruecken-mit-angehobenen-beinen","bankdruecken-in-brueckenstellung","229-bankdruecken-mit-griffstange","230-bankdruecken-mit-griff-am-horn"]},
"bizepscurls":{p:"curl",sk:[["Bizeps",100],["Unterarm",55]],
 b:"Kein Schwung aus dem Rücken. Lieber eine Stufe runter.",
 dt:"Isolationsübung für den Armbeuger. Griffbreite und Griffart verschieben den Reiz zwischen langem und kurzem Bizepskopf.",
 v:["hammer-curls","einarmige-bizepscurls","bizepscurls-mit-griffband","einarmige-bizepscurls-am-seilzug"]},
"trizepsdruecken-am-seilzug":{p:"druck",sk:[["Trizeps",100],["Schultern",30]],
 b:"Ellenbogen bleiben am Körper fixiert.",
 dt:"Am Seilzug bleibt die Spannung über den ganzen Bewegungsweg erhalten — gut als Abschluss nach den Druckübungen.",
 v:["ueberkopf-trizepsdruecken-am-seilzug","einarmiges-trizepsdruecken","trizepsuebung-mit-griffband","066-trizepsuebung-mit-griffstange-kniend"]},
"beinpresse":{p:"druck",sk:[["Quadrizeps",100],["Gesäss",75],["Beinbeuger",40]],
 b:"Knie nicht durchdrücken, unterer Rücken bleibt auf der Bank.",
 dt:"Die Beinpresse erlaubt hohe Lasten bei geringer Belastung der Wirbelsäule — ideal, wenn Kniebeugen im Rücken zwicken.",
 v:["einbeinige-beinpresse","einbeinige-rueckwaertige-beinpresse","hackenschmidt-kniebeuge"]},
"klimmzug-auf-die-brust":{p:"zug",sk:[["Latissimus",100],["Bizeps",65],["Rumpf",45]],
 b:"Nicht aus der gestreckten Hängeposition reissen — Schultern aktiv halten.",
 dt:"Der Klimmzug ist die härteste Zugübung. Über das Griffband lässt sich die Entlastung in Stufen dosieren, statt Wiederholungen abzubrechen.",
 v:["228-klimmzug-mit-griffstange","latzug-zur-brust","haengender-ruderzug-mit-angewinkelten-beinen"]},
"222-fliegende-mit-seilzug-von-unten":{p:"rotation",sk:[["Brust",100],["Schultern",45]],
 b:"Arme leicht gebeugt lassen, nicht durchstrecken.",
 dt:"Der weite Bogen dehnt die Brust unter Last — eine Ergänzung zum Drücken, kein Ersatz.",
 v:["butterfly","flys-einarmig-am-seilzug","224-reverse-flys-vorgebeugt-mit-seilzug"]},
"crunches":{p:"rumpf",sk:[["Gerade Bauchmuskeln",100],["Hüftbeuger",40]],
 b:"Nicht am Nacken ziehen.",
 dt:"Das Einrollen der Wirbelsäule ist die eigentliche Arbeit — nicht das Aufsetzen des Oberkörpers.",
 v:["crunches-mit-griffband","bauchcrunches-seitlich","crossover-crunch-am-seilzug","recrunch-mit-griffband"]},
"stehendes-wadenheben":{p:"hebe",sk:[["Waden",100]],
 b:"Langsam ablassen, die exzentrische Phase ist der Reiz.",
 dt:"Die Wade braucht vollen Bewegungsumfang und viele Wiederholungen — Last ist hier zweitrangig.",
 v:["wadenheben-sitzend","wadenheben-stehend-exzentrisch","219-wadenheben-mit-griff-am-horn"]},
"218-farmers-walk":{p:"rumpf",sk:[["Griffkraft",100],["Rumpf",80],["Trapez",60]],
 b:"Schultern nicht hochziehen, Rippen unten halten.",
 dt:"Tragen unter Last trainiert Griff, Rumpf und Haltung gleichzeitig — der ehrlichste Test der Alltagskraft.",
 v:["220-shrugs-alternierend-mit-griff-am-horn","221-shrugs-mit-griff-am-horn"]},
"rumpfrotation-am-seilzug":{p:"rotation",sk:[["Schräge Bauchmuskeln",100],["Rumpf",65]],
 b:"Aus dem Rumpf rotieren, nicht aus den Armen.",
 dt:"Rotation unter Kontrolle ist das, was im Alltag und im Sport fehlt — langsam ausführen schlägt schwer.",
 v:["russian-twist-am-seilzug","seitliche-crunches-am-seilzug","rumpfrotation"]},
"facepulls-am-seilzug":{p:"zug",sk:[["Hintere Schulter",100],["Oberer Rücken",70],["Rotatoren",50]],
 b:"Leicht beginnen. Diese Übung wirkt über Qualität, nicht über Last.",
 dt:"Die wirksamste Gegenübung zu allem Drücken. Zwei Sätze pro Woche halten die Schulter gesund.",
 v:["226-schulterrotatoren-alternierend-am-seilzug","232-schulterrotatoren-parallel-am-seilzug","224-reverse-flys-vorgebeugt-mit-seilzug"]},
"201-vorgebeugtes-rudern-mit-griffstange":{p:"rudern",sk:[["Oberer Rücken",100],["Latissimus",70],["Bizeps",55]],
 b:"Oberkörperwinkel konstant halten, nicht hochziehen.",
 dt:"Rudern baut die Dicke des Rückens auf — die Ergänzung zum Latzug, der die Breite macht.",
 v:["rudern-vorgebeugt-mit-untergriff","rudern-einarmig","stehendes-rudern-am-seilzug","211-rudern-vorgebeugt-mit-griff-am-horn"]}
};

/* Originaldateiname des GIF je Übung (aus dem EISENHORN-Download).
   Die App lädt zuerst media/<slug>.gif; fehlt die Datei, versucht sie den Originalnamen. */
/* Kandidaten je Übung, in Reihenfolge:
   [0] exakter Dateiname wie heruntergeladen (Umlaute doppelt kodiert),
   [1] bereinigter Name, [2] NFD, [3] ASCII-transliteriert.
   Nach dem Lauf von rename-gifs.sh greift ohnehin media/<slug>.gif. */
window.EH_DATA.GIF = {
"schulterdruecken":["SchulterdrÃ¼cken vor dem Kopf.gif","Schulterdrücken vor dem Kopf.gif","Schulterdrücken vor dem Kopf.gif","Schulterdruecken vor dem Kopf.gif"],
"latzug-in-den-nacken":["Latzug in den Nacken.gif"],
"latzug-zur-brust":["Latzug zur Brust.gif"],
"brustdruecken-stehend":["BrustdrÃ¼cken stehend.gif","Brustdrücken stehend.gif","Brustdrücken stehend.gif","Brustdruecken stehend.gif"],
"bizepscurls":["Bizepscurls stehend.gif"],
"aufrechtes-rudern-mit-engem-griff":["Aufrechtes Rudern mit engem Griff.gif"],
"ruderzug-seitlich-stehend":["Ruderzug seitlich stehend.gif"],
"uebungen-fuer-den-trizeps":["TrizepsÃ¼bung mit Griffstange.gif","Trizepsübung mit Griffstange.gif","Trizepsübung mit Griffstange.gif","Trizepsuebung mit Griffstange.gif"],
"haengendes-beinheben-mit-angewinkelten-beinen":["HÃ¤ngendes Beinheben.gif","Hängendes Beinheben.gif","Hängendes Beinheben.gif","Haengendes Beinheben.gif"],
"recrunch-mit-griffband":["Recrunch mit Griffband.gif"],
"011-trizepsuebung-mit-griffband-kniend":["TrizepsÃ¼bung mit Griffband kniend.gif","Trizepsübung mit Griffband kniend.gif","Trizepsübung mit Griffband kniend.gif","Trizepsuebung mit Griffband kniend.gif"],
"rumpfrotation":["Rumpfrotation.gif"],
"crunches":["Crunches.gif"],
"kreuzheben-mit-griffstange-deadlift":["Kreuzheben mit Griffstange.gif"],
"ausfallschritte":["Ausfallschritte.gif"],
"einbeinige-kniebeuge-mit-entlastung":["Einbeinige Kniebeuge mit Entlastung.gif"],
"einbeinige-beinpresse":["Einbeinige Beinpresse.gif"],
"einbeinige-rueckwaertige-beinpresse":["Einbeinige rÃ¼ckwÃ¤rtige Beinpresse.gif","Einbeinige rückwärtige Beinpresse.gif","Einbeinige rückwärtige Beinpresse.gif","Einbeinige rueckwaertige Beinpresse.gif"],
"stehendes-wadenheben":["Stehendes Wadenheben.gif"],
"beinbeuger-liegend":["Beinbeuger liegend.gif"],
"hackenschmidt-kniebeuge":["Hackenschmidt Kniebeuge.gif"],
"haengendes-beinheben-mit-gestreckten-beinen":["HÃ¤ngendes Beinheben mit gestreckten Beinen.gif","Hängendes Beinheben mit gestreckten Beinen.gif","Hängendes Beinheben mit gestreckten Beinen.gif","Haengendes Beinheben mit gestreckten Beinen.gif"],
"hueftheben-seitlich":["HÃ¼ftheben seitlich.gif","Hüftheben seitlich.gif","Hüftheben seitlich.gif","Hueftheben seitlich.gif"],
"progressives-kreuzheben-mit-griffband":["Progressives Kreuzheben mit Griffband.gif"],
"bankdruecken-brustdruecken":["BankdrÃ¼cken (BrustdrÃ¼cken).gif","Bankdrücken (Brustdrücken).gif","Bankdrücken (Brustdrücken).gif","Bankdruecken (Brustdruecken).gif"],
"beinpresse":["Beinpresse.gif"],
"kniebeugen":["Frontkniebeugen.gif"],
"adduktion-mit-griffband":["Adduktion mit Griffband.gif"],
"rudern-vorgebeugt-mit-untergriff":["Rudern vorgebeugt mit Untergriff.gif"],
"klimmzug-auf-die-brust":["Klimmzug auf die Brust.gif"],
"031-einbeinige-kniebeuge-am-horn":["Einbeinige Kniebeuge am Horn.gif"],
"rudern-seitlich-einarmig":["Rudern seitlich einarmig.gif"],
"brustdruecken-seitlich":["BrustdrÃ¼cken seitlich.gif","Brustdrücken seitlich.gif","Brustdrücken seitlich.gif","Brustdruecken seitlich.gif"],
"innenrotation-mit-seilzug":["Innenrotation mit Seilzug.gif"],
"hueftheben":["HÃ¼ftheben.gif","Hüftheben.gif","Hüftheben.gif","Hueftheben.gif"],
"aussenrotation-mit-seilzug":["Aussenrotation mit Seilzug.gif"],
"rudern-vorgebeugt-mit-obergriff":["Rudern vorgebeugt mit Obergriff.gif"],
"innenrotation-seitlich-mit-griffband":["Innenrotation seitlich mit Griffband.gif"],
"aussenrotation-seitlich-mit-griffband":["Aussenrotation seitlich mit Griffband.gif"],
"beckenheben-liegend":["Beckenheben liegend.gif"],
"aufrechtes-rudern-mit-breitem-griff":["Aufrechtes Rudern mit breitem Griff.gif"],
"trizepsuebung-mit-griffband":["TrizepsÃ¼bung mit Griffband.gif","Trizepsübung mit Griffband.gif","Trizepsübung mit Griffband.gif","Trizepsuebung mit Griffband.gif"],
"schulterdruecken-hinter-dem-kopf":["SchulterdrÃ¼cken hinter dem Kopf.gif","Schulterdrücken hinter dem Kopf.gif","Schulterdrücken hinter dem Kopf.gif","Schulterdruecken hinter dem Kopf.gif"],
"liegestuetze-mit-einem-bein-im-griffband":["LiegestÃ¼tze mit einem Bein im Griffband.gif","Liegestütze mit einem Bein im Griffband.gif","Liegestütze mit einem Bein im Griffband.gif","Liegestuetze mit einem Bein im Griffband.gif"],
"einbeiniges-kreuzheben-einarmig":["Einbeiniges Kreuzheben einarmig.gif"],
"sumo-kreuzheben-deadlifts-mit-griffstange":["Sumo-Kreuzheben (Deadlifts) mit Griffstange.gif"],
"kreuzheben-deadlifts-mit-gestreckten-beinen":["RumÃ¤nisches Kreuzheben.gif","Rumänisches Kreuzheben.gif","Rumänisches Kreuzheben.gif","Rumaenisches Kreuzheben.gif"],
"plank-to-pike":["Plank to pike.gif"],
"ausfallschritte-mit-griffband":["Ausfallschritte mit Griffband.gif"],
"wadenheben-sitzend":["Wadenheben sitzend.gif"],
"unterarm-curls-mit-obergriff":["Unterarm-Curls mit Obergriff.gif"],
"unterarm-curls-hinter-dem-ruecken":["Unterarm-Curls hinter dem RÃ¼cken.gif","Unterarm-Curls hinter dem Rücken.gif","Unterarm-Curls hinter dem Rücken.gif","Unterarm-Curls hinter dem Ruecken.gif"],
"negativ-bankdruecken-mit-angehobenen-beinen":["Negativ BankdrÃ¼cken mit angehobenen Beinen.gif","Negativ Bankdrücken mit angehobenen Beinen.gif","Negativ Bankdrücken mit angehobenen Beinen.gif","Negativ Bankdruecken mit angehobenen Beinen.gif"],
"dips-mit-gewicht":["Dips mit Gewicht.gif"],
"055-haengendes-beinheben-mit-angewinkelten-beinen":["HÃ¤ngendes Beinheben mit angewinkelten Beinen.gif","Hängendes Beinheben mit angewinkelten Beinen.gif","Hängendes Beinheben mit angewinkelten Beinen.gif","Haengendes Beinheben mit angewinkelten Beinen.gif"],
"schienbeinheben-sitzend":["Schienbeinheben sitzend.gif"],
"einbeinige-kniebeugen-seitlich":["Einbeinige Kniebeugen seitlich.gif"],
"crunches-mit-griffband":["Crunches mit Griffband.gif"],
"butterfly":["Butterfly.gif"],
"dips-mit-griffband":["Dips mit Griffband.gif"],
"bauchcrunches-seitlich":["Bauchcrunches seitlich.gif"],
"063-recrunch-mit-griffband":["Recrunch mit Griffband.gif"],
"trizepsuebung-mit-griffband-2":["TrizepsÃ¼bung mit Griffband.gif","Trizepsübung mit Griffband.gif","Trizepsübung mit Griffband.gif","Trizepsuebung mit Griffband.gif"],
"ueberkopf-ausfallschritte":["Ãberkopf-Ausfallschritte.gif","Überkopf-Ausfallschritte.gif","Überkopf-Ausfallschritte.gif","Ueberkopf-Ausfallschritte.gif"],
"066-trizepsuebung-mit-griffstange-kniend":["TrizepsÃ¼bung mit Griffstange kniend.gif","Trizepsübung mit Griffstange kniend.gif","Trizepsübung mit Griffstange kniend.gif","Trizepsuebung mit Griffstange kniend.gif"],
"nackenheben-hinten":["Nackenheben hinten.gif"],
"rudern-einarmig":["Rudern einarmig.gif"],
"bizepscurls-mit-koerpergewicht":["Bizepscurls mit KÃ¶rpergewicht.gif","Bizepscurls mit Körpergewicht.gif","Bizepscurls mit Körpergewicht.gif","Bizepscurls mit Koerpergewicht.gif"],
"ausfallschritte-nach-vorne":["Ausfallschritte nach vorne.gif"],
"schulterheben-hinten":["Schulterheben hinten.gif"],
"072-schulterdruecken-hinter-dem-kopf":["SchulterdrÃ¼cken hinter dem Kopf sitzend.gif","Schulterdrücken hinter dem Kopf sitzend.gif","Schulterdrücken hinter dem Kopf sitzend.gif","Schulterdruecken hinter dem Kopf sitzend.gif"],
"073-dips-mit-griffband-tief":["Dips mit Griffband tief.gif"],
"hammer-curls":["Hammer Curls.gif"],
"haengender-ruderzug-mit-angewinkelten-beinen":["HÃ¤ngender Ruderzug mit angewinkelten Beinen.gif","Hängender Ruderzug mit angewinkelten Beinen.gif","Hängender Ruderzug mit angewinkelten Beinen.gif","Haengender Ruderzug mit angewinkelten Beinen.gif"],
"schulterdruecken-hinter-dem-kopf-mit-griffband":["SchulterdrÃ¼cken hinter dem Kopf mit Griffband.gif","Schulterdrücken hinter dem Kopf mit Griffband.gif","Schulterdrücken hinter dem Kopf mit Griffband.gif","Schulterdruecken hinter dem Kopf mit Griffband.gif"],
"ausfallschritte-mit-griffstange":["Ausfallschritte mit Griffstange.gif"],
"liegestuetze-mit-griffband":["LiegestÃ¼tze mit Griffband.gif","Liegestütze mit Griffband.gif","Liegestütze mit Griffband.gif","Liegestuetze mit Griffband.gif"],
"trizepsdruecken":["TrizepsdrÃ¼cken.gif","Trizepsdrücken.gif","Trizepsdrücken.gif","Trizepsdruecken.gif"],
"mountain-climbers":["Mountain Climbers.gif"],
"schulterdruecken-sitzend":["SchulterdrÃ¼cken sitzend.gif","Schulterdrücken sitzend.gif","Schulterdrücken sitzend.gif","Schulterdruecken sitzend.gif"],
"rumpfbeugen-seitlich":["Rumpfbeugen seitlich.gif"],
"einarmige-bizepscurls":["Einarmige Bizepscurls.gif"],
"rudern-mit-griffband":["Rudern mit Griffband.gif"],
"bankdruecken-in-brueckenstellung":["BankdrÃ¼cken in BrÃ¼ckenstellung.gif","Bankdrücken in Brückenstellung.gif","Bankdrücken in Brückenstellung.gif","Bankdruecken in Brueckenstellung.gif"],
"trizepsuebung-mit-griffband-einarmig":["TrizepsÃ¼bung mit Griffband einarmig.gif","Trizepsübung mit Griffband einarmig.gif","Trizepsübung mit Griffband einarmig.gif","Trizepsuebung mit Griffband einarmig.gif"],
"beinbeuger-mit-griffband":["Beinbeuger mit Griffband.gif"],
"plank-jacks":["Plank Jacks.gif"],
"schulterheben-vorne":["Schulterheben vorne.gif"],
"trizepsuebung-mit-griffstange-im-untergriff":["TrizepsÃ¼bung mit Griffstange Untergriff.gif","Trizepsübung mit Griffstange Untergriff.gif","Trizepsübung mit Griffstange Untergriff.gif","Trizepsuebung mit Griffstange Untergriff.gif"],
"trizepsuebung-mit-griffband-einarmig-2":["TrizepsÃ¼bung mit Griffband einarmig.gif","Trizepsübung mit Griffband einarmig.gif","Trizepsübung mit Griffband einarmig.gif","Trizepsuebung mit Griffband einarmig.gif"],
"wadenheben-stehend-exzentrisch":["Wadenheben stehend exzentrisch.gif"],
"unterarmstuetz-mit-griffband":["UnterarmstÃ¼tz mit Griffband.gif","Unterarmstütz mit Griffband.gif","Unterarmstütz mit Griffband.gif","Unterarmstuetz mit Griffband.gif"],
"094-trizepsuebung-mit-griffstange-untergriff-kniend":["TrizepsÃ¼bung mit Griffstange Untergriff kniend.gif","Trizepsübung mit Griffstange Untergriff kniend.gif","Trizepsübung mit Griffstange Untergriff kniend.gif","Trizepsuebung mit Griffstange Untergriff kniend.gif"],
"latzug-mit-griffband":["Latzug mit Griffband.gif"],
"einbeiniges-kreuzheben":["Einbeiniges Kreuzheben.gif"],
"bizepscurls-mit-griffband":["Bizepscurls mit Griffband.gif"],
"ueberkopf-kniebeugen-overhead-squats":["Ãberkopf-Kniebeugen.gif","Überkopf-Kniebeugen.gif","Überkopf-Kniebeugen.gif","Ueberkopf-Kniebeugen.gif"],
"schulterdruecken-sitzend-mit-angehobenen-fuessen":["SchulterdrÃ¼cken sitzend mit angehobenen FÃ¼ssen.gif","Schulterdrücken sitzend mit angehobenen Füssen.gif","Schulterdrücken sitzend mit angehobenen Füssen.gif","Schulterdruecken sitzend mit angehobenen Fuessen.gif"],
"schulterdruecken-mit-engem-griff":["SchulterdrÃ¼cken mit engem Griff.gif","Schulterdrücken mit engem Griff.gif","Schulterdrücken mit engem Griff.gif","Schulterdruecken mit engem Griff.gif"],
"ausfallschritte-mit-stufe":["Ausfallschritte mit Stufe.gif"],
"laufschritt-mit-griffband":["Laufschritt mit Griffband.gif"],
"liegestuetze-mit-griffband-und-griffstange":["LiegestÃ¼tze mit Griffband und Griffstange.gif","Liegestütze mit Griffband und Griffstange.gif","Liegestütze mit Griffband und Griffstange.gif","Liegestuetze mit Griffband und Griffstange.gif"],
"bizepscurls-mit-griffstange-und-seilzug":["Bizepscurls mit Griffstange und Seilzug.gif"],
"einarmige-bizepscurls-am-seilzug":["Einarmige Bizepscurls am Seilzug.gif"],
"seitenheben-am-seilzug":["Seitenheben am Seilzug.gif"],
"flys-einarmig-am-seilzug":["Flys einarmig am Seilzug.gif"],
"einarmiges-trizepsdruecken":["Einarmiges TrizepsdrÃ¼cken.gif","Einarmiges Trizepsdrücken.gif","Einarmiges Trizepsdrücken.gif","Einarmiges Trizepsdruecken.gif"],
"rumpfrotation-am-seilzug":["Rumpfrotation am Seilzug.gif"],
"110-schulterdruecken-mit-engem-griff-sitzend":["SchulterdrÃ¼cken mit engem Griff sitzend.gif","Schulterdrücken mit engem Griff sitzend.gif","Schulterdrücken mit engem Griff sitzend.gif","Schulterdruecken mit engem Griff sitzend.gif"],
"111-latzug-in-den-nacken-sitzend":["Latzug in den Nacken sitzend.gif"],
"crossover-crunch-am-seilzug":["Crossover Crunch am Seilzug.gif"],
"russian-twist-am-seilzug":["Russian Twist am Seilzug.gif"],
"seitliche-crunches-am-seilzug":["Seitliche Crunches am Seilzug.gif"],
"115-latzug-zur-brust-sitzend":["Latzug zur Brust sitzend.gif"],
"facepulls-am-seilzug":["Facepulls am Seilzug.gif"],
"einarmiger-latzug-am-seilzug":["Einarmiger Latzug am Seilzug.gif"],
"stehendes-rudern-am-seilzug":["Stehendes Rudern am Seilzug.gif"],
"stehendes-rudern-mit-untergriff-am-seilzug":["Stehendes Rudern mit Untergriff am Seilzug.gif"],
"einarmiges-rudern-mit-obergriff-am-seilzug":["Einarmiges Rudern mit Obergriff am Seilzug.gif"],
"rudern-im-ausfallschritt-am-seilzug":["Rudern im Ausfallschritt am Seilzug.gif"],
"stehender-ruderzug-mit-seilzug":["Stehender Ruderzug mit Seilzug.gif"],
"kickbacks-am-seilzug":["Kickbacks am Seilzug.gif"],
"adduktion-am-seilzug":["Adduktion am Seilzug.gif"],
"beinstrecker-am-seilzug":["Beinstrecker am Seilzug.gif"],
"trizepsdruecken-am-seilzug":["TrizepsdrÃ¼cken am Seilzug.gif","Trizepsdrücken am Seilzug.gif","Trizepsdrücken am Seilzug.gif","Trizepsdruecken am Seilzug.gif"],
"ueberkopf-trizepsdruecken-am-seilzug":["Ãberkopf-TrizepsdrÃ¼cken am Seilzug.gif","Überkopf-Trizepsdrücken am Seilzug.gif","Überkopf-Trizepsdrücken am Seilzug.gif","Ueberkopf-Trizepsdruecken am Seilzug.gif"],
"200-schulterdruecken-vor-dem-kopf":["SchulterdrÃ¼cken vor dem Kopf.gif","Schulterdrücken vor dem Kopf.gif","Schulterdrücken vor dem Kopf.gif","Schulterdruecken vor dem Kopf.gif"],
"201-vorgebeugtes-rudern-mit-griffstange":["Vorgebeugtes Rudern mit Griffstange.gif"],
"202-frontkniebeugen":["Frontkniebeugen.gif"],
"203-kniebeugen":["Kniebeugen.gif"],
"204-kreuzheben":["Kreuzheben.gif"],
"205-rumaenisches-kreuzheben":["RumÃ¤nisches Kreuzheben.gif","Rumänisches Kreuzheben.gif","Rumänisches Kreuzheben.gif","Rumaenisches Kreuzheben.gif"],
"206-latzug-mit-griff-am-horn":["Latzug mit Griff am Horn.gif"],
"207-latzug-alternierend-mit-griff-am-horn":["Latzug alternierend mit Griff am Horn.gif"],
"208-latzug-auf-die-brust-mit-griffstange":["Latzug auf die Brust mit Griffstange.gif"],
"209-brustdruecken-stehend-mit-griffstange":["Brustdruecken stehend mit Griffstange.gif"],
"210-schulterdruecken-am-horn-alternierend":["SchulterdrÃ¼cken am Horn alternierend.gif","Schulterdrücken am Horn alternierend.gif","Schulterdrücken am Horn alternierend.gif","Schulterdruecken am Horn alternierend.gif"],
"211-rudern-vorgebeugt-mit-griff-am-horn":["Rudern vorgebeugt mit Griff am Horn.gif"],
"212-vorgebeugtes-rudern-mit-griff-am-horn-alternierend":["vorgebeugtes Rudern mit Griff am Horn alternierend.gif"],
"213-explosives-brustdruecken-am-horn-alternierend":["Explosives BrustdrÃ¼cken am Horn alternierend.gif","Explosives Brustdrücken am Horn alternierend.gif","Explosives Brustdrücken am Horn alternierend.gif","Explosives Brustdruecken am Horn alternierend.gif"],
"214-dips":["Dips.gif"],
"215-kreuzheben-mit-griff-am-horn":["Kreuzheben mit Griff am Horn.gif"],
"216-rumaenisches-kreuzheben-mit-griff-am-horn":["RumÃ¤nisches Kreuzheben mit Griff am Horn.gif","Rumänisches Kreuzheben mit Griff am Horn.gif","Rumänisches Kreuzheben mit Griff am Horn.gif","Rumaenisches Kreuzheben mit Griff am Horn.gif"],
"217-alternierende-dips-stehend":["Alternierende Dips stehend.gif"],
"218-farmers-walk":["Farmer's walk.gif"],
"219-wadenheben-mit-griff-am-horn":["Wadenheben mit Griff am Horn.gif"],
"220-shrugs-alternierend-mit-griff-am-horn":["Shrugs alternierend mit Griff am Horn.gif"],
"221-shrugs-mit-griff-am-horn":["Shrugs mit Griff am Horn.gif"],
"222-fliegende-mit-seilzug-von-unten":["Fliegende mit Seilzug von unten.gif"],
"223-ueberkopf-trizeps-extensions-mit-seilzug":["Ãberkopf-Trizeps-Extensions mit Seilzug.gif","Überkopf-Trizeps-Extensions mit Seilzug.gif","Überkopf-Trizeps-Extensions mit Seilzug.gif","Ueberkopf-Trizeps-Extensions mit Seilzug.gif"],
"224-reverse-flys-vorgebeugt-mit-seilzug":["Reverse Flys vorgebeugt mit Seilzug.gif"],
"225-alterniederendes-rudern-vorgebeugt-mit-seilzug":["Alternierendes Rudern vorgebeugt mit Seilzug.gif"],
"226-schulterrotatoren-alternierend-am-seilzug":["Schulterrotatoren alternierend am Seilzug.gif"],
"227-reverse-flys-asymmetrisch-am-seilzug":["Reverse Flys asymmetrisch am Seilzug.gif"],
"228-klimmzug-mit-griffstange":["Klimmzug mit Griffstange.gif"],
"229-bankdruecken-mit-griffstange":["BankdrÃ¼cken mit Griffstange.gif","Bankdrücken mit Griffstange.gif","Bankdrücken mit Griffstange.gif","Bankdruecken mit Griffstange.gif"],
"230-bankdruecken-mit-griff-am-horn":["BankdrÃ¼cken mit Griff am Horn.gif","Bankdrücken mit Griff am Horn.gif","Bankdrücken mit Griff am Horn.gif","Bankdruecken mit Griff am Horn.gif"],
"231-alternierendes-bankdruecken-mit-griff-am-horn":["Alternierendes BankdrÃ¼cken mit Griff am Horn.gif","Alternierendes Bankdrücken mit Griff am Horn.gif","Alternierendes Bankdrücken mit Griff am Horn.gif","Alternierendes Bankdruecken mit Griff am Horn.gif"],
"232-schulterrotatoren-parallel-am-seilzug":["Schulterrotatoren parallel am Seilzug.gif"]
};
